-- Migration script to add missing columns to existing database
-- Run this script before creating the views

-- Add missing columns to quiz table
ALTER TABLE quiz 
ADD COLUMN IF NOT EXISTS time_limit_minutes INT NULL COMMENT 'Time limit in minutes',
ADD COLUMN IF NOT EXISTS total_questions INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS score INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS max_score INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS status ENUM('IN_PROGRESS', 'COMPLETED', 'ABANDONED') NOT NULL DEFAULT 'IN_PROGRESS',
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add missing columns to user table
ALTER TABLE user
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add missing columns to category table
ALTER TABLE category
ADD COLUMN IF NOT EXISTS description TEXT NULL,
ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add missing columns to question table
ALTER TABLE question
ADD COLUMN IF NOT EXISTS question_type ENUM('MULTIPLE_CHOICE', 'TRUE_FALSE', 'SHORT_ANSWER') NOT NULL DEFAULT 'MULTIPLE_CHOICE',
ADD COLUMN IF NOT EXISTS difficulty_level ENUM('EASY', 'MEDIUM', 'HARD') NOT NULL DEFAULT 'MEDIUM',
ADD COLUMN IF NOT EXISTS points INT NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add missing columns to choice table
ALTER TABLE choice
ADD COLUMN IF NOT EXISTS choice_order INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add missing columns to contact table
ALTER TABLE contact
ADD COLUMN IF NOT EXISTS user_id INT NULL,
ADD COLUMN IF NOT EXISTS status ENUM('NEW', 'READ', 'REPLIED') NOT NULL DEFAULT 'NEW',
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add missing columns to feedback table
ALTER TABLE feedback
ADD COLUMN IF NOT EXISTS user_id INT NULL,
ADD COLUMN IF NOT EXISTS feedback_type ENUM('GENERAL', 'QUIZ', 'BUG_REPORT', 'SUGGESTION') NOT NULL DEFAULT 'GENERAL',
ADD COLUMN IF NOT EXISTS is_resolved BOOLEAN NOT NULL DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;

-- Add foreign key constraints for contact table
ALTER TABLE contact
ADD CONSTRAINT fk_contact_user
FOREIGN KEY (user_id) REFERENCES user(user_id)
ON DELETE SET NULL ON UPDATE CASCADE;

-- Add foreign key constraints for feedback table
ALTER TABLE feedback
ADD CONSTRAINT fk_feedback_user
FOREIGN KEY (user_id) REFERENCES user(user_id)
ON DELETE SET NULL ON UPDATE CASCADE;

-- Create the new quiz_answer table (replaces quizquestion)
CREATE TABLE IF NOT EXISTS quiz_answer (
  answer_id INT NOT NULL AUTO_INCREMENT,
  quiz_id INT NOT NULL,
  question_id INT NOT NULL,
  selected_choice_id INT NULL,
  answer_text TEXT NULL COMMENT 'For short answer questions',
  is_correct BOOLEAN NULL COMMENT 'NULL if not yet graded',
  points_earned INT NOT NULL DEFAULT 0,
  time_taken_seconds INT NULL,
  answered_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (answer_id),
  INDEX fk_answer_quiz_idx (quiz_id ASC),
  INDEX fk_answer_question_idx (question_id ASC),
  INDEX fk_answer_choice_idx (selected_choice_id ASC),
  UNIQUE INDEX idx_quiz_question (quiz_id ASC, question_id ASC),
  CONSTRAINT fk_answer_quiz
    FOREIGN KEY (quiz_id)
    REFERENCES quiz (quiz_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_answer_question
    FOREIGN KEY (question_id)
    REFERENCES question (question_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT fk_answer_choice
    FOREIGN KEY (selected_choice_id)
    REFERENCES choice (choice_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;
